import 'relpmei_base_request.dart';
import '../base/base_request.dart';

/// Modelo base para requisições RELPMEI
class RelpmeiRequest extends RelpmeiBaseRequest {
  RelpmeiRequest({
    required super.contribuinteNumero,
    required super.pedidoDados,
    super.cpfCnpj,
    super.inscricaoEstadual,
    super.codigoReceita,
    super.referencia,
    super.vencimento,
    super.valor,
    super.observacoes,
    super.tipoParcelamento,
    super.numeroParcelas,
    super.valorParcela,
    super.dataVencimento,
    super.codigoBarras,
    super.linhaDigitavel,
    super.dataPagamento,
    super.valorPago,
    super.formaPagamento,
    super.banco,
    super.agencia,
    super.conta,
    super.numeroDocumento,
    super.dataEmissao,
  });

  factory RelpmeiRequest.fromJson(Map<String, dynamic> json) {
    return RelpmeiRequest(
      contribuinteNumero: json['contribuinteNumero'] as String,
      pedidoDados: PedidoDados.fromJson(json['pedidoDados'] as Map<String, dynamic>),
      cpfCnpj: json['cpfCnpj'] as String?,
      inscricaoEstadual: json['inscricaoEstadual'] as String?,
      codigoReceita: json['codigoReceita'] as String?,
      referencia: json['referencia'] as String?,
      vencimento: json['vencimento'] as String?,
      valor: json['valor'] as String?,
      observacoes: json['observacoes'] as String?,
      tipoParcelamento: json['tipoParcelamento'] as String?,
      numeroParcelas: json['numeroParcelas'] as String?,
      valorParcela: json['valorParcela'] as String?,
      dataVencimento: json['dataVencimento'] as String?,
      codigoBarras: json['codigoBarras'] as String?,
      linhaDigitavel: json['linhaDigitavel'] as String?,
      dataPagamento: json['dataPagamento'] as String?,
      valorPago: json['valorPago'] as String?,
      formaPagamento: json['formaPagamento'] as String?,
      banco: json['banco'] as String?,
      agencia: json['agencia'] as String?,
      conta: json['conta'] as String?,
      numeroDocumento: json['numeroDocumento'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
    );
  }
}

/// Modelo para requisição de consulta de pedidos
class ConsultarPedidosRequest extends RelpmeiBaseRequest {
  ConsultarPedidosRequest({
    required super.contribuinteNumero,
    required super.pedidoDados,
    required super.cpfCnpj,
    super.inscricaoEstadual,
    super.codigoReceita,
    super.referencia,
    super.vencimento,
    super.valor,
    super.observacoes,
    super.tipoParcelamento,
    super.numeroParcelas,
    super.valorParcela,
    super.dataVencimento,
    super.codigoBarras,
    super.linhaDigitavel,
    super.dataPagamento,
    super.valorPago,
    super.formaPagamento,
    super.banco,
    super.agencia,
    super.conta,
    super.numeroDocumento,
    super.dataEmissao,
  });

  factory ConsultarPedidosRequest.fromJson(Map<String, dynamic> json) {
    return ConsultarPedidosRequest(
      contribuinteNumero: json['contribuinteNumero'] as String,
      pedidoDados: PedidoDados.fromJson(json['pedidoDados'] as Map<String, dynamic>),
      cpfCnpj: json['cpfCnpj'] as String,
      inscricaoEstadual: json['inscricaoEstadual'] as String?,
      codigoReceita: json['codigoReceita'] as String?,
      referencia: json['referencia'] as String?,
      vencimento: json['vencimento'] as String?,
      valor: json['valor'] as String?,
      observacoes: json['observacoes'] as String?,
      tipoParcelamento: json['tipoParcelamento'] as String?,
      numeroParcelas: json['numeroParcelas'] as String?,
      valorParcela: json['valorParcela'] as String?,
      dataVencimento: json['dataVencimento'] as String?,
      codigoBarras: json['codigoBarras'] as String?,
      linhaDigitavel: json['linhaDigitavel'] as String?,
      dataPagamento: json['dataPagamento'] as String?,
      valorPago: json['valorPago'] as String?,
      formaPagamento: json['formaPagamento'] as String?,
      banco: json['banco'] as String?,
      agencia: json['agencia'] as String?,
      conta: json['conta'] as String?,
      numeroDocumento: json['numeroDocumento'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contribuinteNumero': contribuinteNumero,
      'pedidoDados': pedidoDados.toJson(),
      'cpfCnpj': cpfCnpj,
      'inscricaoEstadual': inscricaoEstadual,
      'codigoReceita': codigoReceita,
      'referencia': referencia,
      'vencimento': vencimento,
      'valor': valor,
      'observacoes': observacoes,
      'tipoParcelamento': tipoParcelamento,
      'numeroParcelas': numeroParcelas,
      'valorParcela': valorParcela,
      'dataVencimento': dataVencimento,
      'codigoBarras': codigoBarras,
      'linhaDigitavel': linhaDigitavel,
      'dataPagamento': dataPagamento,
      'valorPago': valorPago,
      'formaPagamento': formaPagamento,
      'banco': banco,
      'agencia': agencia,
      'conta': conta,
      'numeroDocumento': numeroDocumento,
      'dataEmissao': dataEmissao,
    };
  }
}

/// Modelo para requisição de consulta de parcelamento
class ConsultarParcelamentoRequest extends RelpmeiBaseRequest {
  ConsultarParcelamentoRequest({
    required super.contribuinteNumero,
    required super.pedidoDados,
    required super.cpfCnpj,
    super.inscricaoEstadual,
    super.codigoReceita,
    super.referencia,
    super.vencimento,
    super.valor,
    super.observacoes,
    super.tipoParcelamento,
    super.numeroParcelas,
    super.valorParcela,
    super.dataVencimento,
    super.codigoBarras,
    super.linhaDigitavel,
    super.dataPagamento,
    super.valorPago,
    super.formaPagamento,
    super.banco,
    super.agencia,
    super.conta,
    super.numeroDocumento,
    super.dataEmissao,
  });

  factory ConsultarParcelamentoRequest.fromJson(Map<String, dynamic> json) {
    return ConsultarParcelamentoRequest(
      contribuinteNumero: json['contribuinteNumero'] as String,
      pedidoDados: PedidoDados.fromJson(json['pedidoDados'] as Map<String, dynamic>),
      cpfCnpj: json['cpfCnpj'] as String,
      inscricaoEstadual: json['inscricaoEstadual'] as String?,
      codigoReceita: json['codigoReceita'] as String?,
      referencia: json['referencia'] as String?,
      vencimento: json['vencimento'] as String?,
      valor: json['valor'] as String?,
      observacoes: json['observacoes'] as String?,
      tipoParcelamento: json['tipoParcelamento'] as String?,
      numeroParcelas: json['numeroParcelas'] as String?,
      valorParcela: json['valorParcela'] as String?,
      dataVencimento: json['dataVencimento'] as String?,
      codigoBarras: json['codigoBarras'] as String?,
      linhaDigitavel: json['linhaDigitavel'] as String?,
      dataPagamento: json['dataPagamento'] as String?,
      valorPago: json['valorPago'] as String?,
      formaPagamento: json['formaPagamento'] as String?,
      banco: json['banco'] as String?,
      agencia: json['agencia'] as String?,
      conta: json['conta'] as String?,
      numeroDocumento: json['numeroDocumento'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contribuinteNumero': contribuinteNumero,
      'pedidoDados': pedidoDados.toJson(),
      'cpfCnpj': cpfCnpj,
      'inscricaoEstadual': inscricaoEstadual,
      'codigoReceita': codigoReceita,
      'referencia': referencia,
      'vencimento': vencimento,
      'valor': valor,
      'observacoes': observacoes,
      'tipoParcelamento': tipoParcelamento,
      'numeroParcelas': numeroParcelas,
      'valorParcela': valorParcela,
      'dataVencimento': dataVencimento,
      'codigoBarras': codigoBarras,
      'linhaDigitavel': linhaDigitavel,
      'dataPagamento': dataPagamento,
      'valorPago': valorPago,
      'formaPagamento': formaPagamento,
      'banco': banco,
      'agencia': agencia,
      'conta': conta,
      'numeroDocumento': numeroDocumento,
      'dataEmissao': dataEmissao,
    };
  }
}

/// Modelo para requisição de consulta de parcelas para impressão
class ConsultarParcelasImpressaoRequest extends RelpmeiBaseRequest {
  ConsultarParcelasImpressaoRequest({
    required super.contribuinteNumero,
    required super.pedidoDados,
    required super.cpfCnpj,
    super.inscricaoEstadual,
    super.codigoReceita,
    super.referencia,
    super.vencimento,
    super.valor,
    super.observacoes,
    super.tipoParcelamento,
    super.numeroParcelas,
    super.valorParcela,
    super.dataVencimento,
    super.codigoBarras,
    super.linhaDigitavel,
    super.dataPagamento,
    super.valorPago,
    super.formaPagamento,
    super.banco,
    super.agencia,
    super.conta,
    super.numeroDocumento,
    super.dataEmissao,
  });

  factory ConsultarParcelasImpressaoRequest.fromJson(Map<String, dynamic> json) {
    return ConsultarParcelasImpressaoRequest(
      contribuinteNumero: json['contribuinteNumero'] as String,
      pedidoDados: PedidoDados.fromJson(json['pedidoDados'] as Map<String, dynamic>),
      cpfCnpj: json['cpfCnpj'] as String,
      inscricaoEstadual: json['inscricaoEstadual'] as String?,
      codigoReceita: json['codigoReceita'] as String?,
      referencia: json['referencia'] as String?,
      vencimento: json['vencimento'] as String?,
      valor: json['valor'] as String?,
      observacoes: json['observacoes'] as String?,
      tipoParcelamento: json['tipoParcelamento'] as String?,
      numeroParcelas: json['numeroParcelas'] as String?,
      valorParcela: json['valorParcela'] as String?,
      dataVencimento: json['dataVencimento'] as String?,
      codigoBarras: json['codigoBarras'] as String?,
      linhaDigitavel: json['linhaDigitavel'] as String?,
      dataPagamento: json['dataPagamento'] as String?,
      valorPago: json['valorPago'] as String?,
      formaPagamento: json['formaPagamento'] as String?,
      banco: json['banco'] as String?,
      agencia: json['agencia'] as String?,
      conta: json['conta'] as String?,
      numeroDocumento: json['numeroDocumento'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contribuinteNumero': contribuinteNumero,
      'pedidoDados': pedidoDados.toJson(),
      'cpfCnpj': cpfCnpj,
      'inscricaoEstadual': inscricaoEstadual,
      'codigoReceita': codigoReceita,
      'referencia': referencia,
      'vencimento': vencimento,
      'valor': valor,
      'observacoes': observacoes,
      'tipoParcelamento': tipoParcelamento,
      'numeroParcelas': numeroParcelas,
      'valorParcela': valorParcela,
      'dataVencimento': dataVencimento,
      'codigoBarras': codigoBarras,
      'linhaDigitavel': linhaDigitavel,
      'dataPagamento': dataPagamento,
      'valorPago': valorPago,
      'formaPagamento': formaPagamento,
      'banco': banco,
      'agencia': agencia,
      'conta': conta,
      'numeroDocumento': numeroDocumento,
      'dataEmissao': dataEmissao,
    };
  }
}

/// Modelo para requisição de consulta de detalhes de pagamento
class ConsultarDetalhesPagamentoRequest extends RelpmeiBaseRequest {
  ConsultarDetalhesPagamentoRequest({
    required super.contribuinteNumero,
    required super.pedidoDados,
    required super.cpfCnpj,
    super.inscricaoEstadual,
    super.codigoReceita,
    super.referencia,
    super.vencimento,
    super.valor,
    super.observacoes,
    super.tipoParcelamento,
    super.numeroParcelas,
    super.valorParcela,
    super.dataVencimento,
    super.codigoBarras,
    super.linhaDigitavel,
    super.dataPagamento,
    super.valorPago,
    super.formaPagamento,
    super.banco,
    super.agencia,
    super.conta,
    super.numeroDocumento,
    super.dataEmissao,
  });

  factory ConsultarDetalhesPagamentoRequest.fromJson(Map<String, dynamic> json) {
    return ConsultarDetalhesPagamentoRequest(
      contribuinteNumero: json['contribuinteNumero'] as String,
      pedidoDados: PedidoDados.fromJson(json['pedidoDados'] as Map<String, dynamic>),
      cpfCnpj: json['cpfCnpj'] as String,
      inscricaoEstadual: json['inscricaoEstadual'] as String?,
      codigoReceita: json['codigoReceita'] as String?,
      referencia: json['referencia'] as String?,
      vencimento: json['vencimento'] as String?,
      valor: json['valor'] as String?,
      observacoes: json['observacoes'] as String?,
      tipoParcelamento: json['tipoParcelamento'] as String?,
      numeroParcelas: json['numeroParcelas'] as String?,
      valorParcela: json['valorParcela'] as String?,
      dataVencimento: json['dataVencimento'] as String?,
      codigoBarras: json['codigoBarras'] as String?,
      linhaDigitavel: json['linhaDigitavel'] as String?,
      dataPagamento: json['dataPagamento'] as String?,
      valorPago: json['valorPago'] as String?,
      formaPagamento: json['formaPagamento'] as String?,
      banco: json['banco'] as String?,
      agencia: json['agencia'] as String?,
      conta: json['conta'] as String?,
      numeroDocumento: json['numeroDocumento'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contribuinteNumero': contribuinteNumero,
      'pedidoDados': pedidoDados.toJson(),
      'cpfCnpj': cpfCnpj,
      'inscricaoEstadual': inscricaoEstadual,
      'codigoReceita': codigoReceita,
      'referencia': referencia,
      'vencimento': vencimento,
      'valor': valor,
      'observacoes': observacoes,
      'tipoParcelamento': tipoParcelamento,
      'numeroParcelas': numeroParcelas,
      'valorParcela': valorParcela,
      'dataVencimento': dataVencimento,
      'codigoBarras': codigoBarras,
      'linhaDigitavel': linhaDigitavel,
      'dataPagamento': dataPagamento,
      'valorPago': valorPago,
      'formaPagamento': formaPagamento,
      'banco': banco,
      'agencia': agencia,
      'conta': conta,
      'numeroDocumento': numeroDocumento,
      'dataEmissao': dataEmissao,
    };
  }
}

/// Modelo para requisição de emissão de DAS
class EmitirDasRequest extends RelpmeiBaseRequest {
  EmitirDasRequest({
    required super.contribuinteNumero,
    required super.pedidoDados,
    required super.cpfCnpj,
    super.inscricaoEstadual,
    super.codigoReceita,
    super.referencia,
    super.vencimento,
    super.valor,
    super.observacoes,
    super.tipoParcelamento,
    super.numeroParcelas,
    super.valorParcela,
    super.dataVencimento,
    super.codigoBarras,
    super.linhaDigitavel,
    super.dataPagamento,
    super.valorPago,
    super.formaPagamento,
    super.banco,
    super.agencia,
    super.conta,
    super.numeroDocumento,
    super.dataEmissao,
  });

  factory EmitirDasRequest.fromJson(Map<String, dynamic> json) {
    return EmitirDasRequest(
      contribuinteNumero: json['contribuinteNumero'] as String,
      pedidoDados: PedidoDados.fromJson(json['pedidoDados'] as Map<String, dynamic>),
      cpfCnpj: json['cpfCnpj'] as String,
      inscricaoEstadual: json['inscricaoEstadual'] as String?,
      codigoReceita: json['codigoReceita'] as String?,
      referencia: json['referencia'] as String?,
      vencimento: json['vencimento'] as String?,
      valor: json['valor'] as String?,
      observacoes: json['observacoes'] as String?,
      tipoParcelamento: json['tipoParcelamento'] as String?,
      numeroParcelas: json['numeroParcelas'] as String?,
      valorParcela: json['valorParcela'] as String?,
      dataVencimento: json['dataVencimento'] as String?,
      codigoBarras: json['codigoBarras'] as String?,
      linhaDigitavel: json['linhaDigitavel'] as String?,
      dataPagamento: json['dataPagamento'] as String?,
      valorPago: json['valorPago'] as String?,
      formaPagamento: json['formaPagamento'] as String?,
      banco: json['banco'] as String?,
      agencia: json['agencia'] as String?,
      conta: json['conta'] as String?,
      numeroDocumento: json['numeroDocumento'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contribuinteNumero': contribuinteNumero,
      'pedidoDados': pedidoDados.toJson(),
      'cpfCnpj': cpfCnpj,
      'inscricaoEstadual': inscricaoEstadual,
      'codigoReceita': codigoReceita,
      'referencia': referencia,
      'vencimento': vencimento,
      'valor': valor,
      'observacoes': observacoes,
      'tipoParcelamento': tipoParcelamento,
      'numeroParcelas': numeroParcelas,
      'valorParcela': valorParcela,
      'dataVencimento': dataVencimento,
      'codigoBarras': codigoBarras,
      'linhaDigitavel': linhaDigitavel,
      'dataPagamento': dataPagamento,
      'valorPago': valorPago,
      'formaPagamento': formaPagamento,
      'banco': banco,
      'agencia': agencia,
      'conta': conta,
      'numeroDocumento': numeroDocumento,
      'dataEmissao': dataEmissao,
    };
  }
}
